/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRotasRouteImport } from './routes/_authenticated.rotas'
import { Route as AuthenticatedConferenciaRouteImport } from './routes/_authenticated.conferencia'
import { Route as AuthenticatedAgendarRouteImport } from './routes/_authenticated.agendar'
import { Route as AuthenticatedComprasIndexRouteImport } from './routes/_authenticated.compras.index'
import { Route as AuthenticatedRotasIdRouteImport } from './routes/_authenticated.rotas.$id'
import { Route as AuthenticatedComprasNovaRouteImport } from './routes/_authenticated.compras.nova'
import { Route as AuthenticatedAdminVeiculosRouteImport } from './routes/_authenticated.admin.veiculos'
import { Route as AuthenticatedAdminUtilizadoresRouteImport } from './routes/_authenticated.admin.utilizadores'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated.admin.templates'
import { Route as AuthenticatedAdminTaxasRouteImport } from './routes/_authenticated.admin.taxas'
import { Route as AuthenticatedAdminOtimizacaoRouteImport } from './routes/_authenticated.admin.otimizacao'
import { Route as AuthenticatedAdminEquipaRouteImport } from './routes/_authenticated.admin.equipa'
import { Route as ApiPublicCronGenerateRoutesRouteImport } from './routes/api/public/cron/generate-routes'
import { Route as AuthenticatedRotasIdFecharRouteImport } from './routes/_authenticated.rotas.$id.fechar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRotasRoute = AuthenticatedRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConferenciaRoute =
  AuthenticatedConferenciaRouteImport.update({
    id: '/conferencia',
    path: '/conferencia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendarRoute = AuthenticatedAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComprasIndexRoute =
  AuthenticatedComprasIndexRouteImport.update({
    id: '/compras/',
    path: '/compras/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRotasIdRoute = AuthenticatedRotasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRotasRoute,
} as any)
const AuthenticatedComprasNovaRoute =
  AuthenticatedComprasNovaRouteImport.update({
    id: '/compras/nova',
    path: '/compras/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVeiculosRoute =
  AuthenticatedAdminVeiculosRouteImport.update({
    id: '/admin/veiculos',
    path: '/admin/veiculos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUtilizadoresRoute =
  AuthenticatedAdminUtilizadoresRouteImport.update({
    id: '/admin/utilizadores',
    path: '/admin/utilizadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/admin/templates',
    path: '/admin/templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTaxasRoute = AuthenticatedAdminTaxasRouteImport.update({
  id: '/admin/taxas',
  path: '/admin/taxas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminOtimizacaoRoute =
  AuthenticatedAdminOtimizacaoRouteImport.update({
    id: '/admin/otimizacao',
    path: '/admin/otimizacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEquipaRoute =
  AuthenticatedAdminEquipaRouteImport.update({
    id: '/admin/equipa',
    path: '/admin/equipa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicCronGenerateRoutesRoute =
  ApiPublicCronGenerateRoutesRouteImport.update({
    id: '/api/public/cron/generate-routes',
    path: '/api/public/cron/generate-routes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRotasIdFecharRoute =
  AuthenticatedRotasIdFecharRouteImport.update({
    id: '/fechar',
    path: '/fechar',
    getParentRoute: () => AuthenticatedRotasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agendar': typeof AuthenticatedAgendarRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/rotas': typeof AuthenticatedRotasRouteWithChildren
  '/admin/equipa': typeof AuthenticatedAdminEquipaRoute
  '/admin/otimizacao': typeof AuthenticatedAdminOtimizacaoRoute
  '/admin/taxas': typeof AuthenticatedAdminTaxasRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/admin/veiculos': typeof AuthenticatedAdminVeiculosRoute
  '/compras/nova': typeof AuthenticatedComprasNovaRoute
  '/rotas/$id': typeof AuthenticatedRotasIdRouteWithChildren
  '/compras/': typeof AuthenticatedComprasIndexRoute
  '/rotas/$id/fechar': typeof AuthenticatedRotasIdFecharRoute
  '/api/public/cron/generate-routes': typeof ApiPublicCronGenerateRoutesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agendar': typeof AuthenticatedAgendarRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/rotas': typeof AuthenticatedRotasRouteWithChildren
  '/admin/equipa': typeof AuthenticatedAdminEquipaRoute
  '/admin/otimizacao': typeof AuthenticatedAdminOtimizacaoRoute
  '/admin/taxas': typeof AuthenticatedAdminTaxasRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/admin/veiculos': typeof AuthenticatedAdminVeiculosRoute
  '/compras/nova': typeof AuthenticatedComprasNovaRoute
  '/rotas/$id': typeof AuthenticatedRotasIdRouteWithChildren
  '/compras': typeof AuthenticatedComprasIndexRoute
  '/rotas/$id/fechar': typeof AuthenticatedRotasIdFecharRoute
  '/api/public/cron/generate-routes': typeof ApiPublicCronGenerateRoutesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agendar': typeof AuthenticatedAgendarRoute
  '/_authenticated/conferencia': typeof AuthenticatedConferenciaRoute
  '/_authenticated/rotas': typeof AuthenticatedRotasRouteWithChildren
  '/_authenticated/admin/equipa': typeof AuthenticatedAdminEquipaRoute
  '/_authenticated/admin/otimizacao': typeof AuthenticatedAdminOtimizacaoRoute
  '/_authenticated/admin/taxas': typeof AuthenticatedAdminTaxasRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/utilizadores': typeof AuthenticatedAdminUtilizadoresRoute
  '/_authenticated/admin/veiculos': typeof AuthenticatedAdminVeiculosRoute
  '/_authenticated/compras/nova': typeof AuthenticatedComprasNovaRoute
  '/_authenticated/rotas/$id': typeof AuthenticatedRotasIdRouteWithChildren
  '/_authenticated/compras/': typeof AuthenticatedComprasIndexRoute
  '/_authenticated/rotas/$id/fechar': typeof AuthenticatedRotasIdFecharRoute
  '/api/public/cron/generate-routes': typeof ApiPublicCronGenerateRoutesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agendar'
    | '/conferencia'
    | '/rotas'
    | '/admin/equipa'
    | '/admin/otimizacao'
    | '/admin/taxas'
    | '/admin/templates'
    | '/admin/utilizadores'
    | '/admin/veiculos'
    | '/compras/nova'
    | '/rotas/$id'
    | '/compras/'
    | '/rotas/$id/fechar'
    | '/api/public/cron/generate-routes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agendar'
    | '/conferencia'
    | '/rotas'
    | '/admin/equipa'
    | '/admin/otimizacao'
    | '/admin/taxas'
    | '/admin/templates'
    | '/admin/utilizadores'
    | '/admin/veiculos'
    | '/compras/nova'
    | '/rotas/$id'
    | '/compras'
    | '/rotas/$id/fechar'
    | '/api/public/cron/generate-routes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agendar'
    | '/_authenticated/conferencia'
    | '/_authenticated/rotas'
    | '/_authenticated/admin/equipa'
    | '/_authenticated/admin/otimizacao'
    | '/_authenticated/admin/taxas'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/utilizadores'
    | '/_authenticated/admin/veiculos'
    | '/_authenticated/compras/nova'
    | '/_authenticated/rotas/$id'
    | '/_authenticated/compras/'
    | '/_authenticated/rotas/$id/fechar'
    | '/api/public/cron/generate-routes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicCronGenerateRoutesRoute: typeof ApiPublicCronGenerateRoutesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rotas': {
      id: '/_authenticated/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof AuthenticatedRotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conferencia': {
      id: '/_authenticated/conferencia'
      path: '/conferencia'
      fullPath: '/conferencia'
      preLoaderRoute: typeof AuthenticatedConferenciaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agendar': {
      id: '/_authenticated/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AuthenticatedAgendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compras/': {
      id: '/_authenticated/compras/'
      path: '/compras'
      fullPath: '/compras/'
      preLoaderRoute: typeof AuthenticatedComprasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rotas/$id': {
      id: '/_authenticated/rotas/$id'
      path: '/$id'
      fullPath: '/rotas/$id'
      preLoaderRoute: typeof AuthenticatedRotasIdRouteImport
      parentRoute: typeof AuthenticatedRotasRoute
    }
    '/_authenticated/compras/nova': {
      id: '/_authenticated/compras/nova'
      path: '/compras/nova'
      fullPath: '/compras/nova'
      preLoaderRoute: typeof AuthenticatedComprasNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/veiculos': {
      id: '/_authenticated/admin/veiculos'
      path: '/admin/veiculos'
      fullPath: '/admin/veiculos'
      preLoaderRoute: typeof AuthenticatedAdminVeiculosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/utilizadores': {
      id: '/_authenticated/admin/utilizadores'
      path: '/admin/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AuthenticatedAdminUtilizadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/taxas': {
      id: '/_authenticated/admin/taxas'
      path: '/admin/taxas'
      fullPath: '/admin/taxas'
      preLoaderRoute: typeof AuthenticatedAdminTaxasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/otimizacao': {
      id: '/_authenticated/admin/otimizacao'
      path: '/admin/otimizacao'
      fullPath: '/admin/otimizacao'
      preLoaderRoute: typeof AuthenticatedAdminOtimizacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/equipa': {
      id: '/_authenticated/admin/equipa'
      path: '/admin/equipa'
      fullPath: '/admin/equipa'
      preLoaderRoute: typeof AuthenticatedAdminEquipaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/cron/generate-routes': {
      id: '/api/public/cron/generate-routes'
      path: '/api/public/cron/generate-routes'
      fullPath: '/api/public/cron/generate-routes'
      preLoaderRoute: typeof ApiPublicCronGenerateRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rotas/$id/fechar': {
      id: '/_authenticated/rotas/$id/fechar'
      path: '/fechar'
      fullPath: '/rotas/$id/fechar'
      preLoaderRoute: typeof AuthenticatedRotasIdFecharRouteImport
      parentRoute: typeof AuthenticatedRotasIdRoute
    }
  }
}

interface AuthenticatedRotasIdRouteChildren {
  AuthenticatedRotasIdFecharRoute: typeof AuthenticatedRotasIdFecharRoute
}

const AuthenticatedRotasIdRouteChildren: AuthenticatedRotasIdRouteChildren = {
  AuthenticatedRotasIdFecharRoute: AuthenticatedRotasIdFecharRoute,
}

const AuthenticatedRotasIdRouteWithChildren =
  AuthenticatedRotasIdRoute._addFileChildren(AuthenticatedRotasIdRouteChildren)

interface AuthenticatedRotasRouteChildren {
  AuthenticatedRotasIdRoute: typeof AuthenticatedRotasIdRouteWithChildren
}

const AuthenticatedRotasRouteChildren: AuthenticatedRotasRouteChildren = {
  AuthenticatedRotasIdRoute: AuthenticatedRotasIdRouteWithChildren,
}

const AuthenticatedRotasRouteWithChildren =
  AuthenticatedRotasRoute._addFileChildren(AuthenticatedRotasRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgendarRoute: typeof AuthenticatedAgendarRoute
  AuthenticatedConferenciaRoute: typeof AuthenticatedConferenciaRoute
  AuthenticatedRotasRoute: typeof AuthenticatedRotasRouteWithChildren
  AuthenticatedAdminEquipaRoute: typeof AuthenticatedAdminEquipaRoute
  AuthenticatedAdminOtimizacaoRoute: typeof AuthenticatedAdminOtimizacaoRoute
  AuthenticatedAdminTaxasRoute: typeof AuthenticatedAdminTaxasRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminUtilizadoresRoute: typeof AuthenticatedAdminUtilizadoresRoute
  AuthenticatedAdminVeiculosRoute: typeof AuthenticatedAdminVeiculosRoute
  AuthenticatedComprasNovaRoute: typeof AuthenticatedComprasNovaRoute
  AuthenticatedComprasIndexRoute: typeof AuthenticatedComprasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendarRoute: AuthenticatedAgendarRoute,
  AuthenticatedConferenciaRoute: AuthenticatedConferenciaRoute,
  AuthenticatedRotasRoute: AuthenticatedRotasRouteWithChildren,
  AuthenticatedAdminEquipaRoute: AuthenticatedAdminEquipaRoute,
  AuthenticatedAdminOtimizacaoRoute: AuthenticatedAdminOtimizacaoRoute,
  AuthenticatedAdminTaxasRoute: AuthenticatedAdminTaxasRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminUtilizadoresRoute: AuthenticatedAdminUtilizadoresRoute,
  AuthenticatedAdminVeiculosRoute: AuthenticatedAdminVeiculosRoute,
  AuthenticatedComprasNovaRoute: AuthenticatedComprasNovaRoute,
  AuthenticatedComprasIndexRoute: AuthenticatedComprasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicCronGenerateRoutesRoute: ApiPublicCronGenerateRoutesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
