/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRotasRouteImport } from './routes/_authenticated.rotas'
import { Route as AuthenticatedConferenciaRouteImport } from './routes/_authenticated.conferencia'
import { Route as AuthenticatedAgendarRouteImport } from './routes/_authenticated.agendar'
import { Route as AuthenticatedRotasIdRouteImport } from './routes/_authenticated.rotas.$id'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated.admin.templates'
import { Route as AuthenticatedAdminTaxasRouteImport } from './routes/_authenticated.admin.taxas'
import { Route as ApiPublicCronGenerateRoutesRouteImport } from './routes/api/public/cron/generate-routes'
import { Route as AuthenticatedRotasIdFecharRouteImport } from './routes/_authenticated.rotas.$id.fechar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRotasRoute = AuthenticatedRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConferenciaRoute =
  AuthenticatedConferenciaRouteImport.update({
    id: '/conferencia',
    path: '/conferencia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendarRoute = AuthenticatedAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRotasIdRoute = AuthenticatedRotasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRotasRoute,
} as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/admin/templates',
    path: '/admin/templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTaxasRoute = AuthenticatedAdminTaxasRouteImport.update({
  id: '/admin/taxas',
  path: '/admin/taxas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicCronGenerateRoutesRoute =
  ApiPublicCronGenerateRoutesRouteImport.update({
    id: '/api/public/cron/generate-routes',
    path: '/api/public/cron/generate-routes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRotasIdFecharRoute =
  AuthenticatedRotasIdFecharRouteImport.update({
    id: '/fechar',
    path: '/fechar',
    getParentRoute: () => AuthenticatedRotasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agendar': typeof AuthenticatedAgendarRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/rotas': typeof AuthenticatedRotasRouteWithChildren
  '/admin/taxas': typeof AuthenticatedAdminTaxasRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/rotas/$id': typeof AuthenticatedRotasIdRouteWithChildren
  '/rotas/$id/fechar': typeof AuthenticatedRotasIdFecharRoute
  '/api/public/cron/generate-routes': typeof ApiPublicCronGenerateRoutesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agendar': typeof AuthenticatedAgendarRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/rotas': typeof AuthenticatedRotasRouteWithChildren
  '/admin/taxas': typeof AuthenticatedAdminTaxasRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/rotas/$id': typeof AuthenticatedRotasIdRouteWithChildren
  '/rotas/$id/fechar': typeof AuthenticatedRotasIdFecharRoute
  '/api/public/cron/generate-routes': typeof ApiPublicCronGenerateRoutesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agendar': typeof AuthenticatedAgendarRoute
  '/_authenticated/conferencia': typeof AuthenticatedConferenciaRoute
  '/_authenticated/rotas': typeof AuthenticatedRotasRouteWithChildren
  '/_authenticated/admin/taxas': typeof AuthenticatedAdminTaxasRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/rotas/$id': typeof AuthenticatedRotasIdRouteWithChildren
  '/_authenticated/rotas/$id/fechar': typeof AuthenticatedRotasIdFecharRoute
  '/api/public/cron/generate-routes': typeof ApiPublicCronGenerateRoutesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agendar'
    | '/conferencia'
    | '/rotas'
    | '/admin/taxas'
    | '/admin/templates'
    | '/rotas/$id'
    | '/rotas/$id/fechar'
    | '/api/public/cron/generate-routes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agendar'
    | '/conferencia'
    | '/rotas'
    | '/admin/taxas'
    | '/admin/templates'
    | '/rotas/$id'
    | '/rotas/$id/fechar'
    | '/api/public/cron/generate-routes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agendar'
    | '/_authenticated/conferencia'
    | '/_authenticated/rotas'
    | '/_authenticated/admin/taxas'
    | '/_authenticated/admin/templates'
    | '/_authenticated/rotas/$id'
    | '/_authenticated/rotas/$id/fechar'
    | '/api/public/cron/generate-routes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicCronGenerateRoutesRoute: typeof ApiPublicCronGenerateRoutesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rotas': {
      id: '/_authenticated/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof AuthenticatedRotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conferencia': {
      id: '/_authenticated/conferencia'
      path: '/conferencia'
      fullPath: '/conferencia'
      preLoaderRoute: typeof AuthenticatedConferenciaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agendar': {
      id: '/_authenticated/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AuthenticatedAgendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rotas/$id': {
      id: '/_authenticated/rotas/$id'
      path: '/$id'
      fullPath: '/rotas/$id'
      preLoaderRoute: typeof AuthenticatedRotasIdRouteImport
      parentRoute: typeof AuthenticatedRotasRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/taxas': {
      id: '/_authenticated/admin/taxas'
      path: '/admin/taxas'
      fullPath: '/admin/taxas'
      preLoaderRoute: typeof AuthenticatedAdminTaxasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/cron/generate-routes': {
      id: '/api/public/cron/generate-routes'
      path: '/api/public/cron/generate-routes'
      fullPath: '/api/public/cron/generate-routes'
      preLoaderRoute: typeof ApiPublicCronGenerateRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rotas/$id/fechar': {
      id: '/_authenticated/rotas/$id/fechar'
      path: '/fechar'
      fullPath: '/rotas/$id/fechar'
      preLoaderRoute: typeof AuthenticatedRotasIdFecharRouteImport
      parentRoute: typeof AuthenticatedRotasIdRoute
    }
  }
}

interface AuthenticatedRotasIdRouteChildren {
  AuthenticatedRotasIdFecharRoute: typeof AuthenticatedRotasIdFecharRoute
}

const AuthenticatedRotasIdRouteChildren: AuthenticatedRotasIdRouteChildren = {
  AuthenticatedRotasIdFecharRoute: AuthenticatedRotasIdFecharRoute,
}

const AuthenticatedRotasIdRouteWithChildren =
  AuthenticatedRotasIdRoute._addFileChildren(AuthenticatedRotasIdRouteChildren)

interface AuthenticatedRotasRouteChildren {
  AuthenticatedRotasIdRoute: typeof AuthenticatedRotasIdRouteWithChildren
}

const AuthenticatedRotasRouteChildren: AuthenticatedRotasRouteChildren = {
  AuthenticatedRotasIdRoute: AuthenticatedRotasIdRouteWithChildren,
}

const AuthenticatedRotasRouteWithChildren =
  AuthenticatedRotasRoute._addFileChildren(AuthenticatedRotasRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgendarRoute: typeof AuthenticatedAgendarRoute
  AuthenticatedConferenciaRoute: typeof AuthenticatedConferenciaRoute
  AuthenticatedRotasRoute: typeof AuthenticatedRotasRouteWithChildren
  AuthenticatedAdminTaxasRoute: typeof AuthenticatedAdminTaxasRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendarRoute: AuthenticatedAgendarRoute,
  AuthenticatedConferenciaRoute: AuthenticatedConferenciaRoute,
  AuthenticatedRotasRoute: AuthenticatedRotasRouteWithChildren,
  AuthenticatedAdminTaxasRoute: AuthenticatedAdminTaxasRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicCronGenerateRoutesRoute: ApiPublicCronGenerateRoutesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
